### ISSUE TITLE
Can you please help implementing total bytes reduce counter?

### ISSUE THREAD

**Issue by 0xd34b33f** [kornelski/dupe-krill#10]
[Link to fork](https://github.com/0xd34b33f/dupe-krill)
I think, that the most idiomatic way is updating `Stats` while scanning,  
but I don't fully understand, how your code works.  
My implementaion works awful, cause it shows reduce by 170Gb on 180Gb disk :)

**Comment by kornelski** [comment]
Yeah, this is tricky, since you need to take into account existing *groups* of links. That's why I haven't implemented it yet :)
