### ISSUE TITLE
Non-Critical question  / error report?   "Operation not supported    os error 45" on 

### ISSUE THREAD

**Issue by AD0MZ** [kornelski/dupe-krill#14]
Dear Kornelski:

Thanks so much for sharing your fine utility,  I find it extremely useful.

I'm pretty sure that my issue is MACOS related, and have spent the last two weeks trying to figure out why.  
**Please spend no time on this, I just hoped that you might have a quick thought.  I know the folder structure is mighty deep.**

Out of tens of thousands of files, I get an occasional spate of this error...Operation not supported (os error 45)

It appears that the OS is reporting a problem hard linking with what appears to be a temporary file used by Dupe-Krill
(Congratulations on the XKCD reference BTW...)  XKCD-221 - about random numbers.

unable to hardlink 
/Volumes/M-Backup/RunningBackup 01-01-2022/Documents/Classified/Personal/Farm/Realtor - Paperwork/**Signed by Andrew/Scans From Andrew/Light/Disclosure Statement_ Seller's Disclosure Alternatives -  Strandjord.pdf**

 /Volumes/M-Backup/RunningBackup 01-01-2022/Documents/Classified/Personal/Farm/Realtor - Paperwork/**Scans From Andrew/Light/.tmp-dupe-e1iIQcBFn5pC4MUSm-xkcd-221** due to Operation not supported (os error 45)

/Volumes/M-Backup/RunningBackup 01-01-2022/Documents/Classified/Personal/Farm/Realtor - Paperwork/Scans From Andrew/Light/Disclosure Statement_ Seller's Disclosure Alternatives -  Strandjord.pdf: Operation not supported (os error 45)

What I have.
MacOS 10.14.6, Dupe_Krill  1.4.5 (Jan 3 and previous versions).   EXFAT on external SSD.

I have a duplicate branch of "Scans from Andrew/Light"  in folder "Signed by Andrew" and, in the parent folder of both "Realtor - Paperwork/".

**Comment by kornelski** [comment]
> EXFAT

That's probably the cause. I don't think FAT supports hardlinks at all.

**Comment by AD0MZ** [comment]
Thank you for the kind response, and not making me feel too stupid.

**Comment by AD0MZ** [comment]
Dear Kornel:

Thanks for the very kind response, and not making me feel too stupid.  DUH!
I have closed my question on Github.


I had wondered how Apple was able to “fake” hard links on EXFAT, and the answer that IT CAN’T really helps!!!
Not a whole lot on MAC and EXFAT on the google either….  

The use of Dupe-Krill makes it really easy to get “point in time” snapshots of my entire drive’s folder structure and data, while using only two source drives worth of space.
(Rysnc to a master folder with today’s date.  Later, make a new folder with a new date,  rsync to that one,   Then Dupe-Krill.  Repeat often.

Thank you for making the utility available.

Eric.

**Comment by AD0MZ** [comment]
Dear Kornel:

<   I found this in my drafts, and resent to show you my appreciating for your response, and the find utility…>

Thanks for the very kind response, and not making me feel too stupid.  DUH!

I had wondered how Apple was able to “fake” hard links on EXFAT, and the answer that IT CAN’T really helps!!!
Not a whole lot on MAC and EXFAT on the google either….

The use of Dupe-Krill makes it really easy to get “point in time” snapshots of my entire drive’s folder structure, while using only one source drives worth of space.
(Rysnc to a master folder with today’s date.  Later, make a new folder with a new date,  rsync to that one,   Then Dupe-Krill.  Repeat often.

Thank you for making the utility available.

Eric.
