### ISSUE TITLE
Add Homebrew formula

### ISSUE THREAD

**Issue by eugenesvk** [kornelski/dupe-krill#17]
Would you please add a Homebrew formula like https://github.com/eugenesvk/homebrew-dupe-krill/blob/main/Formula/dupe-krill.rb (can be autoupdated on releases with this github action https://github.com/marketplace/actions/homebrew-bump-formula) to make deduping easier to install/use?

**Comment by kornelski** [comment]
Does it require any changes to this repo? I think anyone can propose a Homebrew formula – so please do that.

**Comment by eugenesvk** [comment]
yes it does, I don't know how to track releases on your repo, so I can only create a "static" formula that would need manual version bumps when this repo releases something new as opposed to you adding a CI workflow that does it automatically after each release and updates your tap (or in the future the hombrew core tap)

Re. proposing to include in the main homebrew repo, don't think it's popular enought to be included there (also that would require change from donwloading your released artifacts to a build from source, which I haven't tried as DL is just simpler)

**Comment by kornelski** [comment]
I have tags for releases: https://github.com/kornelski/dupe-krill/tags

I don't know how Homebrew tracks releases, but it manages to do it for my gifski tool :https://github.com/Homebrew/homebrew-core/blob/92bfa4ee6b2841ecbcd272cdebb4cb004b8e585b/Formula/gifski.rb

**Comment by kornelski** [comment]
that may be it https://docs.brew.sh/Brew-Livecheck

**Comment by eugenesvk** [comment]
Ah, I got confused by a bad memory of failing livechecks due to a change in tagging scheme, but otherwise it's indeed possible to use the linked action to livecheck-poll this repo and upate formula on new tags

Still think it'd be better to have an official formula with an action that's hooked into the app release process directly, but at least the autoupdate issue is solved for me, cheers!

**Comment by kornelski** [comment]
Anyway, the tags exist: https://github.com/kornelski/dupe-krill/tags

**Comment by eugenesvk** [comment]
The tags exist, but the downloads don't, so I see that workflow failing since it can't download the latest tag
