### ISSUE TITLE
Publish as a library?

### ISSUE THREAD

**Issue by Yoric** [kornelski/dupe-krill#7]
Nice tool! Would it be possible to publish `dupe-crill` as a library crate?

I can see other applications:
- trivial plagiarism/open-source violation detection;
- deduplicating samples prior to processing them (actually my current problem);
- smart backups à la Apple Time Machine;
- smart file transfers (without modifying the source directory);
- ...

so it would be nice to be able to use your code for all these purposes!

**Comment by kornelski** [comment]
It's already a library.

**Comment by Yoric** [comment]
Great :)

In that case, you probably want to update the link in Cargo.toml!
